#!/bin/bash

# gitlab-ci-multi-runner data directory
DATA_DIR="/etc/gitlab-runner"
CONFIG_FILE=${CONFIG_FILE:-$DATA_DIR/config.toml}
# custom certificate authority path
CA_CERTIFICATES_PATH=${CA_CERTIFICATES_PATH:-$DATA_DIR/certs/ca.crt}
LOCAL_CA_PATH="/usr/local/share/ca-certificates/ca.crt"

update_ca() {
  echo "Updating CA certificates..."
  cp "${CA_CERTIFICATES_PATH}" "${LOCAL_CA_PATH}"
  update-ca-certificates --fresh >/dev/null
}

if [ -f "${CA_CERTIFICATES_PATH}" ]; then
  # update the ca if the custom ca is different than the current
  cmp -s "${CA_CERTIFICATES_PATH}" "${LOCAL_CA_PATH}" || update_ca
fi

if [ ! -f "${CONFIG_FILE}" ]; then
  # create the configuration file from the environment
  gitlab-runner register -n
  if [ -n "${RUNNER_ENV}" -a -n "${RUNNER_ENV_EXTRA}" ]; then
    sed -i"" -e 's/environment *= *\[\(.*\)\]/environment = [\1, '"${RUNNER_ENV_EXTRA}"']/' "${CONFIG_FILE}"
  fi
  if [ -n "${DOCKER_VOLUMES}" -a -n "${DOCKER_VOLUMES_EXTRA}" ]; then
    sed -i"" -e 's/volumes *= *\[\(.*\)\]/volumes = [\1, '"${DOCKER_VOLUMES_EXTRA}"']/' "${CONFIG_FILE}"
  fi
fi

# launch gitlab-ci-multi-runner passing all arguments
exec gitlab-ci-multi-runner "$@"
